apiVersion: apps/v1
kind: Deployment
metadata:
  name: validator
  namespace: prysm
  labels:
    app: validator
spec:
  selector:
    matchLabels:
      app: validator
  replicas: 1
  strategy: 
    type: Recreate
  template:
    metadata:
      labels:
        app: validator
    spec:
      initContainers:
      - name: init-wait
        image: alpine:3.13.2
        command: ['sh', '-c', 'echo Wait for 780 seconds for extra slashing protection! && sleep 780']
      containers:
      - name: validator
        image: gcr.io/prysmaticlabs/prysm/validator:v1.2.2
        args:
        - --pyrmont 
        - --beacon-rpc-provider=beacon-service.prysm.svc.cluster.local:4000
        - --datadir=/data/prysm/validator
        - --wallet-dir=/data/prysm/validator
        - --wallet-password-file=/data/prysm/wallet/password.txt
        - --graffiti="eth2 x k8s"
        - --accept-terms-of-use
        volumeMounts:
        - name: validator-storage
          mountPath: /data/prysm/validator
          readOnly: false
        - name: wallet-password
          mountPath: /data/prysm/wallet
          readOnly: true
      volumes:
      - name: validator-storage
        hostPath:
          path: /data/prysm/validator
      - name: wallet-password
        secret:
          secretName: wallet-password
          items:
          - key: password
            path: password.txt
      serviceAccountName: validator
      restartPolicy: Always
